predicates
	go
	

clauses
	go:-
	clearwindow,
	write("\nI am EMRAN, All of the worst man. This is my first simple input and output program:\n\n"),
	
	write("Enter a character,integer,real,string value rach:"),
	readchar(C),nl,
	readint(I),
	readreal(R),
	readln(S),nl,nl,

	write("The character value is:",C),nl,
	write("The integer value is:",I),nl,
	write("The real value is:",R),nl,
	write("The string value is:",S),nl.
